config/routes.rb
Rails.application.routes.draw do
  get 'recommends/' => 'recommends#index', as: 'recommends'
  get 'contacts/new'
  post 'contacts/confirm' => 'contacts/confirm'
  post 'contacts/complete' => 'contacts/complete'
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i(index show edit update)
  resources :notes do
    resources :comments, only: %i(create destroy)
    resource :bookmarks, only: %i(create destroy)
    resource :reminds, only: %i(create update destroy)
  end
  resources :users, only: %i(show edit update)
  get 'search' => 'searches#index', as: 'search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :body, presence: true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :reminds, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :entities, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  def bookmarked_by?(user)
    self.bookmarks.where(user_id: user.id).exists?
  end

  def remind_to?(user)
    self.reminds.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    # 現在登録されているタグを配列で取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    # 現在登録するタグと今回登録するタグとの差分を削除
    old_tags = current_tags - sent_tags
    old_tags.each do |old_tag|
      self.tags.delete Tag.find_by(name: old_tag)
    end

    # 今回新規で登録するタグを作成
    new_tags = sent_tags - current_tags
    new_tags.each do |new_tag|
      new_post_tag = Tag.find_or_create_by(name: new_tag)
      self.tags << new_post_tag
    end
  end

  # develop => SQLite, production => MySQLのため
  RANDOM_SORT = Rails.env.production? ? "RAND()" : "RANDOM()"
  def self.random_search(entities)
    return includes(:user).order(RANDOM_SORT).limit(5) unless entities

    column = 'entities.name LIKE?'
    columns, keywords, notes = [], [], []
    entities[0..49].each do |entity|
      # 検索ワードにエンティティを追加していく
      keywords << "%#{entity}%"
      # 検索ワードと'xxx LIKE?'の数を合わせる
      columns << column
      # 'xxx LIKE?'を'or'で繋ぐ
      sql = columns.join(' or ')

      notes = eager_load(:user, :entities).where(sql, *keywords).order(Arel.sql(RANDOM_SORT))

      # ノートが5個以上取得できた時点で終了
      break if notes.count > 5
    end
    notes
  end

  def registration_entities
    # 変種前のエンティティを削除
    entities.destroy_all if entities.present?
    # Natural Language APIよりエンティティを取得
    get_entities = Language.get_data(body)

    # slienceの高い10個をDBに登録
    get_entities[0..9].each do |entity|
      entities.new(
        name: entity['name'],
        salience: entity['salience'],
        category: entity['type'],
        user_id: user_id
        )
    end
  end
end

app/models/remind.rb
class Remind < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :first_notice, presence: true
  validates :second_notice, presence: true
  validates :third_notice, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :notes, through: :tag_maps

  validates :name, presence: true
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :note
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :notes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :fav_notes, through: :bookmarks, source: :note
  has_many :reminds, dependent: :destroy
  has_many :entities, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # ユーザーの全ノートを結合してLanguageに渡すことで
  # ユーザーのエンティティを取得する
  def build_entities
    text = notes.pluck(:body).join
    entities = Language.get_data(text)
    entities.map { |entity| entity['name'] }
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(index show)

  def index
    @column = sort_column
    @direction = sort_direction
    @notes = Note.includes(:user).order(@column => @direction).page(params[:page])
  end

  def show
    if @note.in_private == true && @note.user_id != current_user.id
      redirect_to notes_path
    else
      @comments = @note.comments.all
      @comment = Comment.new
    end
  end

  def new
    @note = Note.new
  end

  def edit
    @tags = @note.tags.pluck(:name) unless @note.tags.nil?
    @tags = @tags.join(" ")
  end

  def create
    @note = current_user.notes.new(note_params)
    tag_list = params[:note][:tag_name].split(nil)
    # エンティティの取得、登録
    @note.registration_entities
    if @note.save
      # sessionの初期化
      session[:note] = nil
      # タグの登録
      @note.save_tag(tag_list)
      # リマインドの作成
      current_user.reminds.find_or_create_by(note_id: @note.id)
      redirect_to note_path(@note), notice: 'ノートが作成されました'
    else
      # フォームから渡された値のみsessionに保存（user_id等は保存しない）
      session[:note] = @note.attributes.slice(*note_params.keys)
      flash[:alert] = @note.errors.full_messages
      redirect_to new_note_path
    end
  end

  def update
    tag_list = params[:note][:tag_name].split(nil)
    # エンティティの取得、更新
    @note.registration_entities
    if @note.update(note_params)
      @note.save_tag(tag_list)
      redirect_to note_path(@note), notice: 'ノートが更新されました'
    else
      flash[:alert] = @note.errors.full_messages
      redirect_to edit_note_path(@note)
    end
  end

  def destroy
    @note.destroy if current_user.id == @note.user.id
    redirect_to notes_path, notice: 'ノートが削除されました'
  end

  private
  def note_params
    params.require(:note).permit(:title, :body, :in_private)
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def sort_column
    params[:column].present? ? params[:column] : 'updated_at'
  end

  def sort_direction
    params[:direction].present? ? params[:direction] : :DESC
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/_form.html.slim
= form_with(model: note, local:true) do |f|
  .field.form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .field.form-group
    = f.label :body
    trix-editor input='note_body' class='h-50 trix-content'
    = f.hidden_field :body, class: 'form-control mt-3', id: 'note_body'

  .form-group
    = f.label :tag_name
    = f.text_field :tag_name, class: 'form-control', value: tags, placeholder: '半角スペースで複数登録可'

  .form-group
    = f.radio_button :in_private, false, checked: !note.in_private
    = f.label :in_private_false, '公開'
    = f.radio_button :in_private, true, checked: note.in_private, class: 'ml-2'
    = f.label :in_private_true, '非公開'
  .actions.form-group
    = f.submit class: 'btn btn-outline-dark btn-sm'

app/views/notes/_index.html.slim
- notes.each do |note|
  - if note.in_private == false || note.user == current_user
    .card.shadow-sm.mb-3
     .card-body
      - if note.in_private == true
        .badge.bg-secondary.text-light 非公開
      = link_to note_path(note) do
        h4.text-truncate = note.title
      i.fas.fa-feather-alt.mr-2
      = link_to user_path(note.user) do
        = note.user.name
      .mt-2
        = "作成：#{note.created_at.strftime('%Y/%m/%d')}"
        br
        = "更新：#{note.updated_at.strftime('%Y/%m/%d')}"
= paginate notes

app/views/notes/_tag.html.slim
.fas.fa-tags
- note.tags.each do |tag|
  = link_to search_path(keyword: tag.name, sort: 'updated_new', model: 'tag') do
    span.badge.bg-secondary.text-light.ml-2
      = tag.name

app/views/notes/edit.html.slim
.container
    .row
        .col.col-lg-10.mx-auto
            = render 'form', note: @note, tags: @tags
            = link_to '削除する', note_path(@note), method: :delete, data: { confirm: '削除しますか？' }, class: 'btn btn-dark btn-sm'
            br
            = link_to '<< Back', request.referer

app/views/notes/index.html.slim
.container
  .row
    .col.col-lg-10.mx-auto
      h1
        span.marker Notes
      = form_with url: notes_path, local: true, method: :get do |f|
        .form-inline.my-3
          = f.select :column, { 更新日: 'updated_at', 作成日: 'created_at' }, { selected: @column }
          = f.select :direction, { 降順: :DESC, 昇順: :ASC }, { selected: @direction },
            { class: 'mx-2'}
          = f.submit '並べ替え', class:"btn btn-outline-dark btn-sm", style: 'height: 28px;'
      = render 'index', notes: @notes

app/views/notes/new.html.slim
.container
    .row
        .col.col-lg-10.mx-auto
            = render 'form', note: @note, tags: @tags
            = link_to '<< Back', request.referer

app/views/notes/show.html.slim
.container
  .row
    .col.col-lg-10.mx-auto
      .d-flex.justify-content-between.align-items-center
        .ml-1
          - if user_signed_in?
            - if @note.user_id == current_user.id
              = link_to edit_note_path(@note), class: 'non-deco' do
                i.far.fa-edit.fa-lg
                | 編集

            - elsif @note.bookmarked_by?(current_user)
              = link_to note_bookmarks_path(@note), method: :delete do
                i.fas.fa-bookmark.fa-lg
            - else
              = link_to note_bookmarks_path(@note), method: :post do
                i.far.fa-bookmark.fa-lg
            span.ml-3.remind-btn
              = render 'reminds/remind_btn', note: @note

        .mr-1.text-right
          = "作成：#{@note.created_at.strftime('%Y/%m/%d')}"
          span.ml-2 = "更新：#{@note.updated_at.strftime('%Y/%m/%d')}"
          br
          | written by
          = link_to user_path(@note.user), class: 'ml-2' do
            = @note.user.name
      .card.shadow
        .card-body
          h1 = @note.title
          = render 'notes/tag', note: @note
          .mt-3
            = sanitize @note.body

      h3.border-bottom.mt-3 comments
      .comments-index
        = render 'comments/index', note: @note, comments: @comments
      -if user_signed_in?
        .comment-form
          = render 'comments/form', note: @note, comment: @comment