config/routes.rb
Rails.application.routes.draw do
  get 'recommends/' => 'recommends#index', as: 'recommends'
  get 'contacts/new'
  post 'contacts/confirm' => 'contacts/confirm'
  post 'contacts/complete' => 'contacts/complete'
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i(index show edit update)
  resources :notes do
    resources :comments, only: %i(create destroy)
    resource :bookmarks, only: %i(create destroy)
    resource :reminds, only: %i(create update destroy)
  end
  resources :users, only: %i(show edit update)
  get 'search' => 'searches#index', as: 'search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :body, presence: true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :reminds, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :entities, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  def bookmarked_by?(user)
    self.bookmarks.where(user_id: user.id).exists?
  end

  def remind_to?(user)
    self.reminds.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    # 現在登録されているタグを配列で取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    # 現在登録するタグと今回登録するタグとの差分を削除
    old_tags = current_tags - sent_tags
    old_tags.each do |old_tag|
      self.tags.delete Tag.find_by(name: old_tag)
    end

    # 今回新規で登録するタグを作成
    new_tags = sent_tags - current_tags
    new_tags.each do |new_tag|
      new_post_tag = Tag.find_or_create_by(name: new_tag)
      self.tags << new_post_tag
    end
  end

  # develop => SQLite, production => MySQLのため
  RANDOM_SORT = Rails.env.production? ? "RAND()" : "RANDOM()"
  def self.random_search(entities)
    return includes(:user).order(RANDOM_SORT).limit(5) unless entities

    column = 'entities.name LIKE?'
    columns, keywords, notes = [], [], []
    entities[0..49].each do |entity|
      # 検索ワードにエンティティを追加していく
      keywords << "%#{entity}%"
      # 検索ワードと'xxx LIKE?'の数を合わせる
      columns << column
      # 'xxx LIKE?'を'or'で繋ぐ
      sql = columns.join(' or ')

      notes = eager_load(:user, :entities).where(sql, *keywords).order(Arel.sql(RANDOM_SORT))

      # ノートが5個以上取得できた時点で終了
      break if notes.count > 5
    end
    notes
  end

  def registration_entities
    # 変種前のエンティティを削除
    entities.destroy_all if entities.present?
    # Natural Language APIよりエンティティを取得
    get_entities = Language.get_data(body)

    # slienceの高い10個をDBに登録
    get_entities[0..9].each do |entity|
      entities.new(
        name: entity['name'],
        salience: entity['salience'],
        category: entity['type'],
        user_id: user_id
        )
    end
  end
end

app/models/remind.rb
class Remind < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :first_notice, presence: true
  validates :second_notice, presence: true
  validates :third_notice, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :notes, through: :tag_maps

  validates :name, presence: true
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :note
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :notes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :fav_notes, through: :bookmarks, source: :note
  has_many :reminds, dependent: :destroy
  has_many :entities, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # ユーザーの全ノートを結合してLanguageに渡すことで
  # ユーザーのエンティティを取得する
  def build_entities
    text = notes.pluck(:body).join
    entities = Language.get_data(text)
    entities.map { |entity| entity['name'] }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact  = Contact.new(contact_params)
    if @contact.valid?
      render :confirm
    else
      flash.now[:alert] = @contact.errors.full_messages
      render :new
    end
  end

  def complete
    @contact = Contact.new(contact_params)
    ContactMailer.received_email(@contact).deliver
    render :complete
  end

  private
  def contact_params
    params.permit(:name, :email, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/complete.html.slim
.container
  .row
    .col.col-lg-10.mx-auto
      h2.mb-5 お問い合わせを承りました。
      = link_to 'トップページへ', root_path

app/views/contacts/confirm.html.slim
.container
  .row
    .col.col-lg-10.mx-auto
      h4.offset-3 入力内容確認
      .d-flex.justify-content-center
        = form_with url: contacts_complete_path, local: true do |f|
          table.table.table-borderless
            tr
              td align='right' = f.label :name
              td  = f.text_field :name, value: @contact.name, readonly: true
            tr
              td align='right' = f.label :email
              td = f.email_field :email, value: @contact.email, readonly: true
            tr
              td align='right' = f.label :message
              td = f.text_area :message, value: @contact.message, rows: 6, id: 'contact-message', readonly: true
            tr
              td
              td = f.submit '送信する', class: 'btn btn-outline-dark btn-sm'

app/views/contacts/new.html.slim
.container
  .row
    .col.col-lg-10.mx-auto
      h4.offset-3 お問い合わせフォーム
      .d-flex.justify-content-center
        = form_with url: contacts_confirm_path, local: true do |f|
          table.table.table-borderless
            tr
              td align='right' = f.label :name
              td  = f.text_field :name, value: @contact.name
            tr
              td align='right' = f.label :email
              td = f.email_field :email, value: @contact.email
            tr
              td align='right' = f.label :message
              td = f.text_area :message, value: @contact.message, rows: 6, id: 'contact-message'
            tr
              td
              td = f.submit '確認画面へ', class: 'btn btn-outline-dark btn-sm'